-- Create app_data table in Supabase
-- Run this in the Supabase SQL Editor to set up the table for attendance data

CREATE TABLE IF NOT EXISTS app_data (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Add RLS (Row Level Security) policy to allow anonymous access
ALTER TABLE app_data ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anonymous access" ON app_data
  FOR ALL
  USING (true)
  WITH CHECK (true);

-- Create index for faster queries
CREATE INDEX idx_app_data_updated_at ON app_data(updated_at DESC);
