// Setup Supabase table for app_data
const { createClient } = require('@supabase/supabase-js');

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (!SUPABASE_URL || !SUPABASE_SERVICE_ROLE_KEY) {
  console.error('Error: SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY not set');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY);

async function setupDatabase() {
  try {
    console.log('🚀 Setting up Supabase database...');

    // Check if table exists by trying to query it
    console.log('✓ Checking if app_data table exists...');
    const { data: tableData, error: tableError } = await supabase
      .from('app_data')
      .select('*', { count: 'exact' })
      .limit(1);

    if (tableError && (tableError.code === '42P01' || tableError.message?.includes('does not exist'))) {
      // Table doesn't exist, print instructions
      console.log('⚠️  Table does not exist. Please run this SQL in Supabase console:');
      console.log('\n' + '='.repeat(60));
      console.log(`
CREATE TABLE IF NOT EXISTS app_data (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  data JSONB NOT NULL DEFAULT '{}',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE app_data ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow anonymous access" ON app_data;

CREATE POLICY "Allow anonymous access" ON app_data
  FOR ALL
  USING (true)
  WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_app_data_updated_at ON app_data(updated_at DESC);
      `);
      console.log('='.repeat(60));
      console.log('\nSteps:');
      console.log('1. Go to https://app.supabase.com');
      console.log('2. Select your project');
      console.log('3. Open SQL Editor');
      console.log('4. Paste and run the above SQL');
      console.log('5. Run this script again\n');
      process.exit(0);
    }

    if (tableError) {
      console.log('⚠️  Error checking table:', tableError.message);
      process.exit(0);
    }

    console.log('✅ Table app_data is ready!');

    // Test insert
    console.log('\n📝 Testing insert...');
    const testData = { classes: [], currentClassIndex: 0 };
    const { data: insertData, error: insertError } = await supabase
      .from('app_data')
      .insert([{ data: testData }])
      .select();

    if (insertError) {
      console.log('⚠️  Insert test error:', insertError.message);
    } else {
      console.log('✅ Insert test successful!');
      console.log('   ID:', insertData[0].id);
    }

    // Test retrieve
    console.log('\n📖 Testing retrieve...');
    const { data: fetchData, error: fetchError } = await supabase
      .from('app_data')
      .select('*')
      .order('id', { ascending: true })
      .limit(1);

    if (fetchError) {
      console.log('⚠️  Fetch test error:', fetchError.message);
    } else {
      console.log('✅ Fetch test successful!');
      console.log('   Records found:', fetchData.length);
      if (fetchData.length > 0) {
        console.log('   Latest data:', JSON.stringify(fetchData[0].data));
      }
    }

    console.log('\n✨ Setup complete! Aplikasi siap digunakan.');
    console.log('\n🌐 Test aplikasi di:');
    console.log('   Production: https://attendance-app-unique.netlify.app');
    console.log('   Lokal (jika netlify dev running): http://localhost:8888');

  } catch (error) {
    console.error('Error during setup:', error.message);
    process.exit(1);
  }
}

setupDatabase();
